### ISSUE TITLE
FsConfig doesn't support JSON Array

### ISSUE THREAD

**Issue by AntyaDev** [demystifyfp/FsConfig#10]
### Description

FsConfig doesn't support JSON Array

### Repro steps

1. Define config.json
here is a JSON:
{
    data: ["1", "2"]
}

2. Define F# type
type Config = {
    Data: string list
}

3. Parse
let config = ConfigurationBuilder()
                        .SetBasePath(Directory.GetCurrentDirectory())
                        .AddJsonFile("config.json")
                        .Build()
                        |> AppConfig

let result = config.Get<Config>()
### Expected behavior

result should contain not empty Config.Data 

### Actual behavior

result contains empty Config.Data 

* Operating system Windows 10 x64

**Comment by demystifyfp** [comment]
Hi @AntyaDev,

Can you try with comma separated string instead of the SON array like below?

```json
{
  "data": "1,2"
}
```
The documention for the list is here https://github.com/demystifyfp/FsConfig#list-type

**Comment by AntyaDev** [comment]
It will not work with complex types.
I mean, 
settings: MySettings list

type MySettings = {
}

**Comment by demystifyfp** [comment]
It is a current limitation. It is due to the fact the list was initially supported for environment variables where we don't have the sophistication of representing a list of a complex type as a string. I am open to a PR or design suggestion if you'd like to contribute.

**Comment by AntyaDev** [comment]
Ah, I see now
> FsConfig is a F# library for reading configuration data from environment variables
It's related only for env variables... I just thought FsConfig means - I can parse any config because the name is very general.

**Comment by demystifyfp** [comment]
@AntyaDev Just to clarify, It [supports AppConfig](https://www.demystifyfp.com/FsConfig/#App-Config) in addition to Env variables with this limitation.
