### ISSUE TITLE
TypeShape conflict

### ISSUE THREAD

**Issue by Rajivhost** [demystifyfp/FsConfig#11]
Hi,
I have a TypeShape conflict when I try to install FsConfig and Equinox.Codec as shown below

![image](https://user-images.githubusercontent.com/3539984/58272042-721aeb80-7d85-11e9-9b6a-fa7a9915668f.png)

Can we hope to have an update of the dependency here?
Best regards,
**Rajiv.**

**Comment by demystifyfp** [comment]
Thanks, @Rajivhost for informing. It's done. Can you verify it with the latest release `2.1.2`?

**Comment by Rajivhost** [comment]
Works now, Thanks!!
