### ISSUE TITLE
Does FsConfig support user-secrets?

### ISSUE THREAD

**Issue by DavidSSL** [demystifyfp/FsConfig#15]
https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=linux

While the above link shows how to set up and and access user secrets, does FsConfig integrate with it? If so are there examples?

**Comment by demystifyfp** [comment]
I guess it should work as the AppConfig is based on IConfigurationRoot which is implemented by the User Secret.

The documentation is available here https://github.com/demystifyfp/FsConfig#dotnet-core-configuration-supported-from-v200-or-above
